version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/runtime_core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/runtime_extensions"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/symlink-reexec"
    schedule:
      interval: "weekly"
